<<<<<<< HEAD
# Site settings
title: Microsoft Technical Case Studies
email: dcaro@microsoft.com
# description: 
baseurl: "/techcasestudies" # the subpath of your site, e.g. /blog/
url: "https://microsoft.github.io" # the base hostname & protocol for your site
twitter_username: dcaro
github_username:  microsoft
encoding: utf-8
use_static_category_list: false # true/false: use true to indicate that site will use 
                               # the static category list to build the category tree. 
                               # Use false to indicate the site to build the category 
                               # tree dynamically using the posts' metadata 

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap
=======
# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
name:             test
title:            test
tagline:          'El blog de test'
description:      'it works on my machine'
url:              http://jmservera.github.io/FagorEderlan
baseurl:          http://jmservera.github.io/
icon:             ''
locale:           es_es

  
paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jmservera/FagorEderlan
>>>>>>> 8c223f46402f8bba7cfcdd782dd3c7905bc602ea
